products: 
  source_metadata: 
    category: source
    title: "Input Product Metadata"
    display_rank: 1
  l1: 
    category: source
    title: "Input Products"
    display_rank: 0
  pixel_qa: 
    category: lsat
    title: "Pixel QA"
    display_rank: 2
  toa: 
    category: lsat
    title: "Top of Atmosphere Reflectance"
    display_rank: 0
  bt: 
    category: lsat
    title: "Brightness Temperature"
    display_rank: 1
  cloud: 
    category: lsat
    title: "Cloud Mask"
    display_rank: -1
  sr: 
    category: cdr
    title: "Surface Reflectance"
    display_rank: 0
  lst: 
    category: cdr
    title: "Land Surface Temperature"
    display_rank: 1
  swe: 
    category: ecv
    title: "Dynamic Surface Water Extent"
    display_rank: 0
  sr_ndvi: 
    category: indices
    title: "NDVI"
    display_rank: 0
  sr_evi: 
    category: indices
    title: "EVI"
    display_rank: 1
  sr_savi: 
    category: indices
    title: "SAVI"
    display_rank: 2
  sr_msavi: 
    category: indices
    title: "MSAVI"
    display_rank: 3
  sr_ndmi: 
    category: indices
    title: "NDMI"
    display_rank: 4
  sr_nbr: 
    category: indices
    title: "NBR"
    display_rank: 5
  sr_nbr2: 
    category: indices
    title: "NBR2"
    display_rank: 6
  stats: 
    category: stats
    title: "Summary Statistics"
    display_rank: 0

categories: 
  source:
    title: "Source Products"
    display_rank: 0
  cdr:
    title: "Climate Data Records"
    display_rank: 1
  ecv:
    title: "Essential Climate Variables"
    display_rank: 2
  lsat:
    title: "Other Landsat Level-2 Products"
    display_rank: 3
  indices:
    title: "Spectral Indices"
    display_rank: 4
  stats:
    title: "Plotting & Statistics"
    display_rank: 5
